# Eureka ??? ????? ???? ???? ?? ?? ??? ???? ??
server:
  port: 8761

# ???? ???? ???? Spring Cloud, Spring Boot ???????
# ???? ???? ??? ID? ???? ??? ? ID? ???? name? ????.
spring:
  application:
    name: discoveryservice

# Eureka ?????? ???? Spring Boot? ????
# ????? Eureka ?????? ???? ???? ???? ??? ???? ??.
# ?? ?? ???? ???? ??? ????? true? ????
# ?? ???? ???? ????? ??? ??????
# ????? ??? ??? ???? ???? ??? false? ?????.
#
# ??
# ?? ??? Eureka ?? ??? ??? ??
# ?? ??? ??? ??? ?? ?? ???? ????
# Eureka ????? ?? ??? ???? ??? ? ??? ?? ??.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false